export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';

export const INCREMENT = 'INCREMENT';
export const RESET = 'RESET';

export const FILTER_SELECTED = 'FILTER_SELECTED';
export const SELECT_ARTICLE = 'SELECT_ARTICLE';
export const SELECT_DATES = 'SELECT_DATES';

export const ADD_COMMENT = 'ADD_COMMENT';
